keeleinstituut/tv-authorization

- application/app/Http/Controllers/InstitutionUserController.php
- application/app/Policies/InstitutionUserPolicy.php
- application/composer.json
- application/composer.lock
- application/routes/api.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerExportTest.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerShowTest.php
- application/tests/Feature/RepresentationHelpers.php
Resolves issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/149
> #149: create endpoint for exporting users of current institution

- application/app/Enums/DefaultRole.php
Updates issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/101
Change idea approved by Birgit in [this Slack thread](https://pundar.slack.com/archives/C048W5ZV1ST/p1685538509763499?thread_ts=1685537379.965249&cid=C048W5ZV1ST).
> Update #101: Include every privilege in the default "Institution Main User" role

- application/app/Enums/PrivilegeKey.php
- application/database/migrations/2023_06_07_122214_insert_privileges.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/184
> feat(184) - add tag related privileges

- application/app/Observers/InstitutionObserver.php
- application/app/Observers/InstitutionUserObserver.php
This caused root role protections to fail
> FIX: remove $afterCommit=true property from observers

- application/app/Http/Requests/UpdateInstitutionUserRequest.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerUpdateTest.php
- application/tests/TestCase.php
Relevant GitHub issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/137
Problem reported by Inga in https://pundar.slack.com/archives/C053FD55ATT/p1689784135714679
> fix(#137): Allow editing deactivated users

- application/app/Http/Controllers/InstitutionUserController.php
Issue reported by Kaarel: https://pundar.slack.com/archives/C053FD55ATT/p1689607688678019
> #149: Set exported CSV delimiter to semicolon

- application/app/Console/Commands/DetachRolesFromDeactivatedUsers.php
- application/app/Http/Requests/DeactivateInstitutionUserRequest.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerDeactivateTest.php
GitHub Issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/294
Problem reported by Inga in https://pundar.slack.com/archives/C053FD55ATT/p1689669667234609
> #294: Reject adding deactivation_date on users who are sole root role holders

- application/app/Http/Requests/UpdateInstitutionUserRequest.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerUpdateTest.php
* Relevant GitHub issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/137
* Problem as reported: https://pundar.slack.com/archives/C053FD55ATT/p1689791947937539?thread_ts=1689784135.714679&cid=C053FD55ATT
> fix(#137): Disallow role modification on deactivated users

- application/app/Http/Controllers/InstitutionUserController.php
- application/app/Http/Requests/InstitutionUserListRequest.php
- application/tests/Feature/Http/Controllers/InstitutionUserControllerIndexTest.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/430
> feat(#430) - Add search institution user by name

- application/app/Helpers/CsvReader.php
- application/app/Http/Controllers/InstitutionUserController.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/409
> fix(#409) - Add skip of UTF-8 BOM bytes

- application/app/Enums/PrivilegeKey.php
- application/database/migrations/2023_10_12_085443_insert_view_institution_price_rate_privilege.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/306
> feat(#306) - add `VIEW_INSTITUTION_PRICE_RATE` privilege

- application/app/Http/Controllers/InstitutionUserSyncController.php
- application/app/Http/Resources/Sync/InstitutionUserSyncResource.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/633
> feat(#505) - Remove deactivated && archived users from the sync

- application/database/migrations/2023_12_19_152608_insert_export_institution_general_report_privilege.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/178
> feat(#178) - add `EXPORT_INSTITUTION_GENERAL_REPORT` privilege

- application/app/Http/Kernel.php
- application/app/Http/Middleware/XssSanitization.php
- application/app/Http/Requests/API/RoleCreateRequest.php
- application/app/Http/Requests/API/RoleUpdateRequest.php
- application/app/Http/Requests/Helpers/MaxLengthValue.php
- application/app/Http/Requests/StoreDepartmentRequest.php
- application/app/Http/Requests/UpdateCurrentInstitutionUserRequest.php
- application/app/Http/Requests/UpdateDepartmentRequest.php
- application/app/Http/Requests/UpdateInstitutionRequest.php
- application/app/Http/Requests/UpdateInstitutionUserRequest.php
- application/app/Rules/UserFullNameRule.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/605
improved input validation && added converting of special characters to HTML entities.
> feat(#605) - input validation

- application/app/Enums/PrivilegeKey.php
- application/database/migrations/2024_01_15_085041_insert_view_institution_unclaimed_project_detail_privilege.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/358
> feat(#358) - add missing privilege

- application/app/Http/Requests/UpdateCurrentInstitutionUserRequest.php
- application/app/Http/Requests/UpdateInstitutionUserRequest.php
- application/app/Rules/UserFullNameRule.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/645
> feat(#645) - improve username validation

- application/app/Enums/PrivilegeKey.php
- application/database/migrations/2024_03_01_113916_rename_receive_and_namange_project_privilege_key.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/619
Related PR: https://github.com/keeleinstituut/tv-translation-order/pull/132
> feat(#619) - rename `RECEIVE_AND_MANAGE_PROJECT` to `RECEIVE_PROJECT`

- application/app/Policies/InstitutionUserPolicy.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/783
> feat(#783) - Allow editing of personal data

- application/app/Helpers/WorktimeValidationUtil.php
- application/app/Http/Controllers/InstitutionController.php
- application/app/Http/Requests/UpdateInstitutionRequest.php
- application/app/Http/Requests/UpdateInstitutionUserRequest.php
- application/app/Policies/InstitutionPolicy.php
- application/database/factories/InstitutionFactory.php
Issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/193#issuecomment-2182446889
add proper permissions check for the institution update endpoint
> feat(#193): Managing institution user working times

- application/app/Policies/InstitutionVacationPolicy.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/785
> feat(#785): remove privilege check  for viewing institution vacations

- application/app/Http/Requests/UpdateInstitutionUserRequest.php
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/796#issuecomment-2522292250
> feat(#796):  institution user worktime update

- application/composer.json
- application/composer.lock
Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/836
> feat(#836): amqp dependency update
